### ISSUE TITLE
Upgrade code to Tensorflow 2.0

### ISSUE THREAD

**Issue by ghost** [orybkin/sigma-vae-tensorflow#3]
The code is more difficult to understand than the same thing written using Keras, please change that, I want to use the code for a college project but it is difficult to change it to use Keras.

**Comment by orybkin** [comment]
It should be very easy to add the method to any TF2.0 VAE code. You can take the example code (https://www.tensorflow.org/tutorials/generative/cvae) and add the method following the commits in my repo.
